version: '3.8'

services:
  postgres: 
    image: postgres
    container_name: financeapp_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: financeapp
    ports: 
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
